In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt

In [2]:
df1 = pd.read_csv('uber.csv')

In [3]:
df1.drop(labels='Unnamed: 0',axis=1,inplace=True)

In [4]:
df1

key  fare_amount          pickup_datetime  \
0         2015-05-07 19:52:06.0000003          7.5  2015-05-07 19:52:06 UTC   
1         2009-07-17 20:04:56.0000002          7.7  2009-07-17 20:04:56 UTC   
2        2009-08-24 21:45:00.00000061         12.9  2009-08-24 21:45:00 UTC   
3         2009-06-26 08:22:21.0000001          5.3  2009-06-26 08:22:21 UTC   
4       2014-08-28 17:47:00.000000188         16.0  2014-08-28 17:47:00 UTC   
...                               ...          ...                      ...   
199995   2012-10-28 10:49:00.00000053          3.0  2012-10-28 10:49:00 UTC   
199996    2014-03-14 01:09:00.0000008          7.5  2014-03-14 01:09:00 UTC   
199997   2009-06-29 00:42:00.00000078         30.9  2009-06-29 00:42:00 UTC   
199998    2015-05-20 14:56:25.0000004         14.5  2015-05-20 14:56:25 UTC   
199999   2010-05-15 04:08:00.00000076         14.1  2010-05-15 04:08:00 UTC   

        pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.999817        40.738354         -73.999512   
1             -73.994355        40.728225         -73.994710   
2             -74.005043        40.740770         -73.962565   
3             -73.976124        40.790844         -73.965316   
4             -73.925023        40.744085         -73.973082   
...                  ...              ...                ...   
199995        -73.987042        40.739367         -73.986525   
199996        -73.984722        40.736837         -74.006672   
199997        -73.986017        40.756487         -73.858957   
199998        -73.997124        40.725452         -73.983215   
199999        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  
0              40.723217                1  
1              40.750325                1  
2              40.772647                1  
3              40.803349                3  
4              40.761247                5  
...                  ...              ...  
199995         40.740297                1  
199996         40.739620                1  
199997         40.692588                2  
199998         40.695415                1  
199999         40.768793                1  

[200000 rows x 8 columns]

In [5]:
df1.isnull().sum()

key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [6]:
# df.dropna(inplace=True)

In [7]:
df1.fillna(value={'dropoff_longitude':df1['dropoff_longitude'].mean(),'dropoff_latitude':df1['dropoff_latitude'].mean()},inplace=True)

In [8]:
df1.describe()

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
count  200000.000000     200000.000000    200000.000000      200000.000000   
mean       11.359955        -72.527638        39.935885         -72.525292   
std         9.901776         11.437787         7.720539          13.117375   
min       -52.000000      -1340.648410       -74.015515       -3356.666300   
25%         6.000000        -73.992065        40.734796         -73.991407   
50%         8.500000        -73.981823        40.752592         -73.980093   
75%        12.500000        -73.967154        40.767158         -73.963658   
max       499.000000         57.418457      1644.421482        1153.572603   

       dropoff_latitude  passenger_count  
count     200000.000000    200000.000000  
mean          39.923890         1.684535  
std            6.794812         1.385997  
min         -881.985513         0.000000  
25%           40.733823         1.000000  
50%           40.753042         1.000000  
75%           40.768001         2.000000  
max          872.697628       208.000000

In [9]:
df1['pickup_datetime'] =  pd.to_datetime(df1['pickup_datetime'])

In [10]:
df1

key  fare_amount           pickup_datetime  \
0         2015-05-07 19:52:06.0000003          7.5 2015-05-07 19:52:06+00:00   
1         2009-07-17 20:04:56.0000002          7.7 2009-07-17 20:04:56+00:00   
2        2009-08-24 21:45:00.00000061         12.9 2009-08-24 21:45:00+00:00   
3         2009-06-26 08:22:21.0000001          5.3 2009-06-26 08:22:21+00:00   
4       2014-08-28 17:47:00.000000188         16.0 2014-08-28 17:47:00+00:00   
...                               ...          ...                       ...   
199995   2012-10-28 10:49:00.00000053          3.0 2012-10-28 10:49:00+00:00   
199996    2014-03-14 01:09:00.0000008          7.5 2014-03-14 01:09:00+00:00   
199997   2009-06-29 00:42:00.00000078         30.9 2009-06-29 00:42:00+00:00   
199998    2015-05-20 14:56:25.0000004         14.5 2015-05-20 14:56:25+00:00   
199999   2010-05-15 04:08:00.00000076         14.1 2010-05-15 04:08:00+00:00   

        pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.999817        40.738354         -73.999512   
1             -73.994355        40.728225         -73.994710   
2             -74.005043        40.740770         -73.962565   
3             -73.976124        40.790844         -73.965316   
4             -73.925023        40.744085         -73.973082   
...                  ...              ...                ...   
199995        -73.987042        40.739367         -73.986525   
199996        -73.984722        40.736837         -74.006672   
199997        -73.986017        40.756487         -73.858957   
199998        -73.997124        40.725452         -73.983215   
199999        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  
0              40.723217                1  
1              40.750325                1  
2              40.772647                1  
3              40.803349                3  
4              40.761247                5  
...                  ...              ...  
199995         40.740297                1  
199996         40.739620                1  
199997         40.692588                2  
199998         40.695415                1  
199999         40.768793                1  

[200000 rows x 8 columns]

In [11]:
df1['hour'] = df1['pickup_datetime'].dt.hour
df1['dayofweek'] =  df1['pickup_datetime'].dt.dayofweek

In [12]:
df = df1.drop(columns=['key','pickup_datetime'],axis=1)
df

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
0               7.5        -73.999817        40.738354         -73.999512   
1               7.7        -73.994355        40.728225         -73.994710   
2              12.9        -74.005043        40.740770         -73.962565   
3               5.3        -73.976124        40.790844         -73.965316   
4              16.0        -73.925023        40.744085         -73.973082   
...             ...               ...              ...                ...   
199995          3.0        -73.987042        40.739367         -73.986525   
199996          7.5        -73.984722        40.736837         -74.006672   
199997         30.9        -73.986017        40.756487         -73.858957   
199998         14.5        -73.997124        40.725452         -73.983215   
199999         14.1        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  hour  dayofweek  
0              40.723217                1    19          3  
1              40.750325                1    20          4  
2              40.772647                1    21          0  
3              40.803349                3     8          4  
4              40.761247                5    17          3  
...                  ...              ...   ...        ...  
199995         40.740297                1    10          6  
199996         40.739620                1     1          4  
199997         40.692588                2     0          0  
199998         40.695415                1    14          2  
199999         40.768793                1     4          5  

[200000 rows x 8 columns]

In [13]:
X = df.drop(columns=['fare_amount'],axis=1)
y = df['fare_amount']

In [14]:
X

pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.999817        40.738354         -73.999512   
1             -73.994355        40.728225         -73.994710   
2             -74.005043        40.740770         -73.962565   
3             -73.976124        40.790844         -73.965316   
4             -73.925023        40.744085         -73.973082   
...                  ...              ...                ...   
199995        -73.987042        40.739367         -73.986525   
199996        -73.984722        40.736837         -74.006672   
199997        -73.986017        40.756487         -73.858957   
199998        -73.997124        40.725452         -73.983215   
199999        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  hour  dayofweek  
0              40.723217                1    19          3  
1              40.750325                1    20          4  
2              40.772647                1    21          0  
3              40.803349                3     8          4  
4              40.761247                5    17          3  
...                  ...              ...   ...        ...  
199995         40.740297                1    10          6  
199996         40.739620                1     1          4  
199997         40.692588                2     0          0  
199998         40.695415                1    14          2  
199999         40.768793                1     4          5  

[200000 rows x 7 columns]

In [15]:
y

0          7.5
1          7.7
2         12.9
3          5.3
4         16.0
          ... 
199995     3.0
199996     7.5
199997    30.9
199998    14.5
199999    14.1
Name: fare_amount, Length: 200000, dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=30)1

In [17]:
Scaler = StandardScaler()

In [18]:
X_Scaler_train = Scaler.fit_transform(X_train)
X_Scaler_test = Scaler.fit_transform(X_test)

In [19]:
from scipy import stats
z_scores = stats.zscore(df['fare_amount'])
outliers = (z_scores > 3) | (z_scores < -3)
outlier_indices = df.index[outliers]

df = df.drop(outlier_indices)

In [20]:
correlation = X_train.corr()

In [21]:
correlation

pickup_longitude  pickup_latitude  dropoff_longitude  \
pickup_longitude           1.000000        -0.892184           0.838550   
pickup_latitude           -0.892184         1.000000          -0.948209   
dropoff_longitude          0.838550        -0.948209           1.000000   
dropoff_latitude          -0.878877         0.921147          -0.907928   
passenger_count           -0.001548         0.000325          -0.000180   
hour                       0.001627        -0.003600           0.003559   
dayofweek                  0.002223        -0.002801           0.001092   

                   dropoff_latitude  passenger_count      hour  dayofweek  
pickup_longitude          -0.878877        -0.001548  0.001627   0.002223  
pickup_latitude            0.921147         0.000325 -0.003600  -0.002801  
dropoff_longitude         -0.907928        -0.000180  0.003559   0.001092  
dropoff_latitude           1.000000         0.000061 -0.002340  -0.003499  
passenger_count            0.000061         1.000000  0.012278   0.033598  
hour                      -0.002340         0.012278  1.000000  -0.087980  
dayofweek                 -0.003499         0.033598 -0.087980   1.000000

In [22]:
linear_model = LinearRegression()
linear_model.fit(X_Scaler_train,y_train)

LinearRegression()

In [23]:
lasso = Lasso(alpha=1.0)
lasso.fit(X_Scaler_train,y_train)

Lasso()

In [24]:
ridge = Ridge(alpha=1.0)
ridge.fit(X_Scaler_train,y_train)

Ridge()

In [25]:
linear_prediction = linear_model.predict(X_Scaler_test)
linear_prediction

array([11.29827219, 11.81025062, 11.0337338 , ..., 11.09765261,
       11.19787927, 11.29847315])

In [26]:
lasso_prediction = lasso.predict(X_Scaler_test)
lasso_prediction

array([11.34096219, 11.34096219, 11.34096219, ..., 11.34096219,
       11.34096219, 11.34096219])

In [27]:
ridge_prediction = ridge.predict(X_Scaler_test)
ridge_prediction

array([11.29827254, 11.81024781, 11.03373593, ..., 11.09765384,
       11.19787994, 11.29847325])

In [28]:
r2_linear = r2_score(y_test, linear_prediction)
rmse_linear = sqrt(mean_squared_error(y_test, linear_prediction))

In [29]:
r2_lasso = r2_score(y_test, lasso_prediction)
rmse_lasso = sqrt(mean_squared_error(y_test, lasso_prediction))

In [30]:
r2_ridge = r2_score(y_test, ridge_prediction)
rmse_ridge = sqrt(mean_squared_error(y_test, ridge_prediction))

In [31]:
print(f"Linear Regression - R2: {r2_linear}, RMSE: {rmse_linear}")
print(f"Ridge Regression - R2: {r2_ridge}, RMSE: {rmse_ridge}")
print(f"Lasso Regression - R2: {r2_lasso}, RMSE: {rmse_lasso}")

Linear Regression - R2: 0.0007134010854721318, RMSE: 10.317741355915086
Ridge Regression - R2: 0.0007134014070252492, RMSE: 10.31774135425505
Lasso Regression - R2: -8.465464503859543e-05, RMSE: 10.321860539181973
